export interface AppShowcaseBrand {
  name: string;
  slug: string;
  bg: string;
  lightLogo?: boolean;
}

export const APP_SHOWCASE_BRANDS: AppShowcaseBrand[] = [
  { name: 'Shopify', slug: 'shopify', bg: '#96bf48' },
  { name: 'Spotify', slug: 'spotify', bg: '#1db954' },
  { name: 'TikTok', slug: 'tiktok', bg: '#010101' },
  { name: 'Snapchat', slug: 'snapchat', bg: '#fffc00', lightLogo: true },
  { name: 'PayPal', slug: 'paypal', bg: '#003087' },
  { name: 'Instagram', slug: 'instagram', bg: '#e4405f' },
  { name: 'Pinterest', slug: 'pinterest', bg: '#bd081c' },
  { name: 'Mailchimp', slug: 'mailchimp', bg: '#ffe01b', lightLogo: true },
  { name: 'Meta', slug: 'meta', bg: '#0866ff' },
  { name: 'Stripe', slug: 'stripe', bg: '#635bff' },
  { name: 'Amazon', slug: 'amazon', bg: '#ff9900' },
  { name: 'eBay', slug: 'ebay', bg: '#e53238' },
  { name: 'Etsy', slug: 'etsy', bg: '#f16521' },
  { name: 'WooCommerce', slug: 'woocommerce', bg: '#96588a' },
  { name: 'Square', slug: 'square', bg: '#3e4348' },
  { name: 'FedEx', slug: 'fedex', bg: '#4d148c' },
  { name: 'UPS', slug: 'ups', bg: '#351c15' },
  { name: 'DHL', slug: 'dhl', bg: '#ffcc00', lightLogo: true },
  { name: 'Zendesk', slug: 'zendesk', bg: '#03363d' },
  { name: 'Intercom', slug: 'intercom', bg: '#1f8ded' },
  { name: 'HubSpot', slug: 'hubspot', bg: '#ff7a59' },
  { name: 'Slack', slug: 'slack', bg: '#4a154b' },
  { name: 'YouTube', slug: 'youtube', bg: '#ff0000' },
  { name: 'X', slug: 'x', bg: '#000000' },
  { name: 'LinkedIn', slug: 'linkedin', bg: '#0a66c2' },
  { name: 'WhatsApp', slug: 'whatsapp', bg: '#25d366' },
  { name: 'Apple', slug: 'apple', bg: '#000000' },
  { name: 'Google', slug: 'google', bg: '#4285f4' },
  { name: 'Microsoft', slug: 'microsoft', bg: '#5e5e5e' },
  { name: 'Notion', slug: 'notion', bg: '#000000' },
  { name: 'Airtable', slug: 'airtable', bg: '#18bfff' },
  { name: 'Zapier', slug: 'zapier', bg: '#ff4a00' },
  { name: 'Twilio', slug: 'twilio', bg: '#f22f46' },
  { name: 'Afterpay', slug: 'afterpay', bg: '#b2fce4', lightLogo: true },
  { name: 'Klarna', slug: 'klarna', bg: '#ffb3c7', lightLogo: true },
  { name: 'Trustpilot', slug: 'trustpilot', bg: '#00b67a' },
  { name: 'Google Ads', slug: 'googleads', bg: '#4285f4' },
  { name: 'Google Analytics', slug: 'googleanalytics', bg: '#e37400' },
  { name: 'Discord', slug: 'discord', bg: '#5865f2' },
  { name: 'Telegram', slug: 'telegram', bg: '#26a5e4' },
  { name: 'Salesforce', slug: 'salesforce', bg: '#00a1e0' },
  { name: 'QuickBooks', slug: 'quickbooks', bg: '#2ca01c' },
  { name: 'Xero', slug: 'xero', bg: '#13b5ea' },
  { name: 'Revolut', slug: 'revolut', bg: '#0075eb' },
  { name: 'Wise', slug: 'wise', bg: '#9fe870', lightLogo: true },
  { name: 'Coinbase', slug: 'coinbase', bg: '#0052ff' },
  { name: 'Visa', slug: 'visa', bg: '#1a1f71' },
  { name: 'Mastercard', slug: 'mastercard', bg: '#eb001b' },
  { name: 'American Express', slug: 'americanexpress', bg: '#2e77bc' },
  { name: 'Alipay', slug: 'alipay', bg: '#1677ff' },
  { name: 'WeChat', slug: 'wechat', bg: '#07c160' },
  { name: 'Payoneer', slug: 'payoneer', bg: '#ff4800' },
  { name: 'Mailgun', slug: 'mailgun', bg: '#f06b66' },
  { name: 'Heroku', slug: 'heroku', bg: '#430098' },
  { name: 'Vercel', slug: 'vercel', bg: '#000000' },
  { name: 'Netlify', slug: 'netlify', bg: '#00c7b7' },
  { name: 'GitHub', slug: 'github', bg: '#181717' },
  { name: 'GitLab', slug: 'gitlab', bg: '#fc6d26' },
  { name: 'Docker', slug: 'docker', bg: '#2496ed' },
  { name: 'Kubernetes', slug: 'kubernetes', bg: '#326ce5' },
  { name: 'React', slug: 'react', bg: '#20232a' },
  { name: 'Angular', slug: 'angular', bg: '#dd0031' },
  { name: 'BigCommerce', slug: 'bigcommerce', bg: '#121118' },
  { name: 'Magento', slug: 'magento', bg: '#ee672f' },
  { name: 'Adobe', slug: 'adobe', bg: '#ff0000' },
  { name: 'Canva', slug: 'canva', bg: '#00c4cc' },
  { name: 'Figma', slug: 'figma', bg: '#f24e1e' },
  { name: 'Dropbox', slug: 'dropbox', bg: '#0061ff' },
  { name: 'Trello', slug: 'trello', bg: '#0052cc' },
  { name: 'Asana', slug: 'asana', bg: '#f06a6a' },
  { name: 'Shopware', slug: 'shopware', bg: '#189eff' },
  { name: 'Big Cartel', slug: 'bigcartel', bg: '#222222' },
];
