export const APP_ROUTE_PATHS = {
  home: '',
  company: 'firma',
  contact: 'kontakt',
  news: 'aktualnosci',
  partnerships: 'wspolprace',
  login: 'login',
  register: 'register',
  forgotPassword: 'forgot-password',
  resetPassword: 'reset-password',
  dashboard: 'dashboard',
  profile: 'profil',
  deposit: 'depozyt',
  transactions: 'transakcje',
  campaignCreator: 'kreator-kampanii',
  markets: 'rynki',
  myCampaigns: 'moje-kampanie',
  accountTypes: 'rodzaje-kont',
  changePassword: 'zmiana-hasla',
} as const;
