export const APP_ROUTE_PATHS = {
  home: '',
  company: 'firma',
  contact: 'kontakt',
  partnerships: 'wspolprace',
  login: 'login',
  register: 'register',
  dashboard: 'dashboard',
  profile: 'profil',
  deposit: 'depozyt',
  transactions: 'transakcje',
  campaignCreator: 'kreator-kampanii',
  markets: 'rynki',
  myCampaigns: 'moje-kampanie',
  changePassword: 'zmiana-hasla',
} as const;
