export const APP_ROUTE_PATHS = {
  home: '',
  company: 'company',
  contact: 'contact',
  news: 'news',
  partnerships: 'partnerships',
  login: 'login',
  register: 'register',
  forgotPassword: 'forgot-password',
  resetPassword: 'reset-password',
  activate: 'activate',
  dashboard: 'dashboard',
  profile: 'profile',
  deposit: 'deposit',
  transactions: 'transactions',
  campaignCreator: 'campaign-creator',
  markets: 'markets',
  myCampaigns: 'my-campaigns',
  accountTypes: 'account-types',
  changePassword: 'change-password',
} as const;
