#!/usr/bin/env python3
"""Build flat i18n key map per locale for partnerships detail pages."""
import json
from pathlib import Path

OUT = Path(__file__).resolve().parent / "partnerships-detail-i18n-data.json"

BLOCK_TITLES = {
    "pl": ("Marka zdefiniowana przez rozdziały", "Budowanie doświadczenia", "Globalny zasięg"),
    "en": ("A brand defined by chapters", "Crafting the experience", "Global reach"),
    "de": ("Eine Marke, definiert in Kapiteln", "Das Erlebnis gestalten", "Globale Reichweite"),
    "fr": ("Une marque définie par des chapitres", "Construire l'expérience", "Portée mondiale"),
    "ru": ("Бренд, определённый главами", "Создание опыта", "Глобальный охват"),
    "pt": ("Uma marca definida por capítulos", "Construindo a experiência", "Alcance global"),
}

SHARED = {
    "pl": {
        "marketing.partnerships.detail.back": "← Wróć do współprac",
        "marketing.partnerships.detail.nextProject": "Poznaj kolejną realizację",
        "marketing.partnerships.detail.viewAll": "Zobacz wszystkie współprace",
    },
    "en": {
        "marketing.partnerships.detail.back": "← Back to partnerships",
        "marketing.partnerships.detail.nextProject": "Explore the next project",
        "marketing.partnerships.detail.viewAll": "View all partnerships",
    },
    "de": {
        "marketing.partnerships.detail.back": "← Zurück zu Partnerschaften",
        "marketing.partnerships.detail.nextProject": "Das nächste Projekt entdecken",
        "marketing.partnerships.detail.viewAll": "Alle Partnerschaften anzeigen",
    },
    "fr": {
        "marketing.partnerships.detail.back": "← Retour aux partenariats",
        "marketing.partnerships.detail.nextProject": "Découvrir le prochain projet",
        "marketing.partnerships.detail.viewAll": "Voir tous les partenariats",
    },
    "ru": {
        "marketing.partnerships.detail.back": "← Назад к партнёрствам",
        "marketing.partnerships.detail.nextProject": "Следующий проект",
        "marketing.partnerships.detail.viewAll": "Все партнёрства",
    },
    "pt": {
        "marketing.partnerships.detail.back": "← Voltar às parcerias",
        "marketing.partnerships.detail.nextProject": "Conheça o próximo projeto",
        "marketing.partnerships.detail.viewAll": "Ver todas as parcerias",
    },
}

LOCALES = ("pl", "en", "de", "fr", "ru", "pt")

def L(pl, en, de, fr, ru, pt):
    return dict(zip(LOCALES, (pl, en, de, fr, ru, pt)))

# tuple order: intro, outroTitle, outro, b1body, b1alt, b2body, b3body, b3alt
PROJECTS = {}

PROJECTS["cheekbone"] = L(
    ("Cheekbone Beauty to marka beauty założona przez przedsiębiorczynię z plemienia Anishinaabe, która od lat buduje kosmetyki w duchu reprezentacji i odpowiedzialności społecznej. Kampania Glossed Over stanęła przed dylematem całej kategorii: jak wyróżnić się w estetyce glossy bez wyrzeczenia się autentycznej historii. Naszym zadaniem było nadać tej historii format godny globalnej sceny.", "Piękno, które zostaje", "Glossed Over pokazało, że rdzenna przedsiębiorczość i światowy kaliber produkcji nie wykluczają się — a społeczność w centrum marki może stać się jej najsilniejszym kanałem wzrostu.", "Zamiast jednej wielkiej obietnicy rozłożyliśmy narrację na rozdziały: tożsamość założycielki, skład formuł, wpływ na społeczność. Każdy rozdział miał własny rytm wizualny, ale wspólną oś — uczciwość wobec klientek, które od lat traktują Cheekbone jak głos, na który można liczyć.", "Strategia wizualna kampanii Glossed Over dla Cheekbone Beauty", "Od krótkich form w social mediach po hero kampanii — zaprojektowaliśmy ścieżkę, na której produkt nie jest dodatkiem do reklamy, lecz bohaterem opowieści. Makijaż, tekstura i światło pracowały jak jeden język: glossy, ale nigdy pusty.", "Kampania zyskała zasięg poza kanadyjską niszę beauty, otwierając dialog z międzynarodową publicznością szukającą marek z wartościami. Glossed Over stało się punktem odniesienia dla kolejnych premier linii Cheekbone.", "Globalna kampania Glossed Over Cheekbone Beauty w kanałach digital"),
    ("Cheekbone Beauty is an Indigenous-owned cosmetics brand built on representation and social responsibility. Glossed Over faced a category dilemma: stand out in a glossy aesthetic without abandoning an authentic story. We gave that story a format worthy of the global stage.", "Beauty that endures", "Glossed Over proved Indigenous entrepreneurship and world-class production can coexist—and a community-centered brand can become its strongest growth channel.", "Instead of one big promise, we structured chapters: founder identity, formula integrity, community impact—each with its own visual rhythm and one axis of honesty toward loyal customers.", "Visual strategy for the Glossed Over campaign, Cheekbone Beauty", "From social shorts to campaign hero, the product leads the story. Makeup, texture, and light speak one language: glossy, never empty.", "The campaign reached beyond Canada's beauty niche, engaging global audiences seeking values-led brands and anchoring future Cheekbone launches.", "Global Glossed Over campaign for Cheekbone Beauty across digital channels"),
    ("Cheekbone Beauty ist eine von Indigenen geführte Kosmetikmarke, die Repräsentation und Verantwortung verbindet. Glossed Over musste in einer glossy Ästhetik bestehen, ohne die echte Geschichte zu verlieren—wir gaben ihr ein Format für die globale Bühne.", "Schönheit, die bleibt", "Glossed Over zeigte: indigenes Unternehmertum und Weltklasse-Produktion schließen sich nicht aus—die Community kann zum stärksten Wachstumskanal werden.", "Kapitel statt eines großen Versprechens: Identität der Gründerin, Formeln, Community-Impact—jeweils eigener visueller Rhythmus, eine Achse der Ehrlichkeit.", "Visuelle Strategie für Glossed Over, Cheekbone Beauty", "Von Social-Clips bis Hero: das Produkt trägt die Story. Make-up, Textur und Licht als eine Sprache—glossy, nie leer.", "Die Kampagne erreichte internationale Zielgruppen jenseits der kanadischen Nische und wurde Referenz für weitere Cheekbone-Launches.", "Globale Glossed-Over-Kampagne von Cheekbone Beauty im Digitalbereich"),
    ("Cheekbone Beauty est une marque de beauté fondée par une entrepreneure autochtone, bâtie sur la représentation et la responsabilité sociale. Glossed Over devait briller sans trahir l'histoire authentique—nous lui avons donné une forme digne de la scène mondiale.", "Une beauté qui dure", "Glossed Over a prouvé que l'entrepreneuriat autochtone et une production de classe mondiale vont de pair—la communauté peut devenir le principal levier de croissance.", "Des chapitres plutôt qu'une promesse unique : identité de la fondatrice, formules, impact communautaire—chaque rythme visuel, une même exigence d'honnêteté.", "Stratégie visuelle de la campagne Glossed Over pour Cheekbone Beauty", "Des formats sociaux au hero de campagne, le produit mène le récit. Maquillage, texture et lumière parlent le même langage—glossy, jamais vide.", "La campagne a dépassé la niche canadienne et dialogué avec un public international en quête de marques à valeurs.", "Campagne mondiale Glossed Over pour Cheekbone Beauty sur les canaux digitaux"),
    ("Cheekbone Beauty — косметический бренд под управлением коренных предпринимателей, строящий продукт на представительстве и ответственности. Glossed Over должна была выделиться в glossy-эстетике, не теряя подлинной истории.", "Красота, которая остаётся", "Glossed Over показала: коренное предпринимательство и мировой уровень производства совместимы — сообщество может стать главным каналом роста.", "Главы вместо одного обещания: личность основательницы, состав формул, влияние на сообщество — единая ось честности к клиентам.", "Визуальная стратегия кампании Glossed Over для Cheekbone Beauty", "От коротких social-форматов до hero-кампании продукт в центре истории. Макияж, текстура и свет — один язык: glossy, но не пустой.", "Кампания вышла за пределы канадской ниши и открыла диалог с глобальной аудиторией, ищущей ценностные бренды.", "Глобальная кампания Glossed Over Cheekbone Beauty в digital-каналах"),
    ("A Cheekbone Beauty é uma marca de beleza de propriedade indígena, construída em representação e responsabilidade social. Glossed Over precisava destacar-se na estética glossy sem abandonar a história autêntica— demos a essa história um formato à altura do palco global.", "Beleza que permanece", "Glossed Over provou que empreendedorismo indígena e produção de classe mundial coexistem—a comunidade no centro da marca pode ser seu maior canal de crescimento.", "Capítulos em vez de uma promessa única: identidade da fundadora, fórmulas, impacto na comunidade—cada ritmo visual com o mesmo eixo de honestidade.", "Estratégia visual da campanha Glossed Over para Cheekbone Beauty", "De formatos sociais ao hero da campanha, o produto lidera a narrativa. Maquiagem, textura e luz falam a mesma língua—glossy, nunca vazia.", "A campanha ultrapassou o nicho canadense e dialogou com públicos globais em busca de marcas com valores.", "Campanha global Glossed Over da Cheekbone Beauty nos canais digitais"),
)

PROJECTS["bimber"] = L(
    ("Bimber to polska marka, która łączy tradycję destylacji z nowoczesną kulturą muzyczną. Serial przy pełni księżyca miał przekształcić produkt kategorii premium w rytuał — nie kolejną reklamę alkoholu, lecz wieczór z charakterem. Wyzwaniem było zbudowanie platformy contentowej, która brzmi autentycznie na scenie i w e-commerce jednocześnie.", "Noc, która sprzedaje historię", "Pełnia księżyca stała się sygnaturą Bimber: regularnym momentem spotkania fanów, artystów i marki — i dowodem, że serialowa narracja może napędzać sprzedaż tak samo skutecznie jak klasyczna kampania ATL.", "Opowiedzieliśmy Bimber przez rozdziały smaku, miejsca i brzmienia — od leśnej destylarni po scenę koncertową. Strategia nie opierała się na haśle, lecz na sezonowości: każda pełnia to nowy rozdział z własnym artystą, setlistą i wizualnym kodem.", "Strategia serialu muzycznego Bimber przy pełni księżyca", "Live stream, clipy, materiały behind-the-scenes i sklep online działały jak jeden wieczór rozciągnięty w czasie. Widz mógł wejść w środek rytuału, a fan mógł kupić butelkę, która pachnie tym samym wieczorem.", "Format zyskał oddanie w Polsce i zainteresowanie partnerów zagranicznych szukających lokalnych historii z potencjałem eksportu narracji. Serial ugruntował Bimber jako markę eventową, nie tylko etykietę na półce.", "Zasięg serialu muzycznego Bimber w kanałach digital i eventowych"),
    ("Bimber is a Polish brand pairing distilling heritage with contemporary music culture. The full-moon music series had to turn a premium spirit into a ritual—not another alcohol ad, but an evening with character. We needed a content platform authentic on stage and in e-commerce alike.", "A night that sells the story", "The full moon became Bimber's signature—a recurring meet-up of fans, artists, and brand, proving serialized storytelling can drive sales like classic ATL.", "We told Bimber in chapters of taste, place, and sound—from forest distillery to concert stage. Strategy relied on seasonality: each full moon, a new artist, setlist, and visual code.", "Strategy for Bimber's full-moon music series", "Live streams, clips, BTS, and the shop worked as one evening over time. Viewers entered the ritual; fans bought the bottle that smelled like that night.", "The format earned loyalty in Poland and interest from partners seeking local stories with exportable narratives. Bimber became an event brand, not only a shelf label.", "Reach of Bimber's music series across digital and event channels"),
    ("Bimber verbindet Destilliertradition mit zeitgenössischer Musikkultur. Die Vollmond-Serie sollte Premium-Spirituosen zum Ritual machen—keine weitere Alkoholwerbung, sondern ein Abend mit Charakter.", "Eine Nacht, die die Story verkauft", "Der Vollmond wurde Bimbers Signatur und bewies, dass Serienstorytelling Umsatz wie ATL treiben kann.", "Kapitel von Geschmack, Ort und Klang—vom Wald bis zur Bühne. Saisonalität statt Slogan: jeder Vollmond ein neues Kapitel.", "Strategie der Bimber-Vollmond-Musikserie", "Streams, Clips, BTS und Shop als ein Abend über die Zeit. Zuschauer im Ritual, Fans mit der Flasche dieses Nachts.", "Treue in Polen und internationales Partnerinteresse. Bimber als Event-Marke verankert.", "Reichweite der Bimber-Serie in Digital und Events"),
    ("Bimber associe tradition de distillation et culture musicale actuelle. La série des pleines lunes devait faire du spiritueux premium un rituel—pas une pub d'alcool de plus, mais une soirée avec caractère.", "Une nuit qui vend l'histoire", "La pleine lune est devenue la signature de Bimber—preuve qu'une narration en série peut vendre comme l'ATL.", "Chapitres de goût, de lieu et de son—de la distillerie à la scène. Saisonnalité : chaque pleine lune, nouvel artiste et code visuel.", "Stratégie de la série musicale Bimber aux pleines lunes", "Streams, clips, coulisses et boutique comme une même soirée étirée. Le public entre dans le rituel ; les fans achètent la bouteille de cette nuit.", "Fidélité en Pologne et intérêt de partenaires internationaux. Bimber comme marque événementielle.", "Portée de la série Bimber en digital et événements"),
    ("Bimber сочетает традиции дистилляции и современную музыкальную культуру. Сериал при полнолунии должен был превратить премиальный продукт в ритуал — не очередную рекламу алкоголя, а вечер с характером.", "Ночь, которая продаёт историю", "Полнолуние стало визитной карточкой Bimber — доказательством, что серийный сторителлинг продаёт не хуже классического ATL.", "Главы вкуса, места и звука — от лесной дистиллерии до сцены. Сезонность: каждое полнолуние — новый артист и визуальный код.", "Стратегия музыкального сериала Bimber при полнолунии", "Стримы, клипы, закулисье и магазин как один вечер во времени. Зритель в ритуале, фанат с бутылкой этой ночи.", "Лояльность в Польше и интерес международных партнёров. Bimber как event-бренд.", "Охват сериала Bimber в digital и ивентах"),
    ("A Bimber une tradição da destilação à cultura musical contemporânea. A série das luas cheias devia transformar um destilado premium em ritual—não mais um anúncio de álcool, mas uma noite com caráter.", "Uma noite que vende a história", "A lua cheia tornou-se a assinatura da Bimber—prova de que narrativa em série vende como o ATL clássico.", "Capítulos de sabor, lugar e som—da destilaria à palco. Sazonalidade: cada lua cheia, novo artista e código visual.", "Estratégia da série musical Bimber à lua cheia", "Streams, clipes, bastidores e loja como uma noite estendida. O público entra no ritual; fãs compram a garrafa daquela noite.", "Fidelidade na Polónia e interesse de parceiros internacionais. Bimber como marca de eventos.", "Alcance da série Bimber em digital e eventos"),
)

PROJECTS["youthFoundation"] = L(
    ("Fundacja wspierająca młodzież potrzebowała kampanii, która przebije się przez zmęczenie tematami charytatywnymi — bez patosu i bez chłodu statystyk. Młodzi ludzie mieli stać się bohaterami opowieści, nie beneficjentami slajdu. Naszym celem było połączenie emocji z konkretnym wezwaniem do działania.", "Głos, który ma przyszłość", "Kampania prospołeczna przekroczyła jednorazowy peak donacji: zostawiła szablony treści i partnerów medialnych, którzy dziś wracają do historii fundacji w kolejnych sezonach.", "Zamiast jednego uniwersalnego przekazu zbudowaliśmy rozdziały: szkoła, pierwsza praca, kryzys, wsparcie mentora. Każdy rozdział miał twarz i cytat uczestnika programu — strategia oparta na prawdziwych ścieżkach, nie na abstrakcyjnej „pomocy”.", "Strategia narracyjna kampanii prospołecznej fundacji wspierającej młodzież", "Spot wideo, karuzele social, landing z historiami i prosty mechanizm darowizny tworzyły jedną ścieżkę: poznaj człowieka, zrozum kontekst, zrób krok. Projektowaliśmy język wizualny, który jest ciepły, ale nie infantylny.", "Materiały zostały zaadaptowane przez partnerów lokalnych i regionalnych mediów, zwiększając zasięg bez utraty intymności historii. Fundacja zyskała rozpoznawalny format kampanii na lata.", "Zasięg kampanii prospołecznej fundacji w mediach i social media"),
    ("A youth foundation needed a campaign that breaks through charity fatigue—without melodrama or cold stats. Young people had to be story heroes, not slide beneficiaries. We paired emotion with a clear call to action.", "A voice with a future", "The campaign moved past a one-time donation spike, leaving templates and media partners who return each season.", "Chapters—not one message: school, first job, crisis, mentor support. Each had a face and quote from participants—strategy on real paths, not abstract 'help.'", "Narrative strategy for the youth foundation social campaign", "Video, social carousels, stories landing, and simple donate flow: meet the person, understand context, act. Warm visual language, not childish.", "Local and regional media adapted assets, extending reach without losing intimacy. A recognizable campaign format for years.", "Reach of the youth foundation campaign in media and social"),
    ("Eine Jugendstiftung brauchte eine Kampagne gegen Spendenmüdigkeit—ohne Pathos oder kalte Statistik. Jugendliche als Helden, nicht als Folienempfänger.", "Eine Stimme mit Zukunft", "Über einen Spendenspitzen hinaus: Vorlagen und Medienpartner für jede Saison.", "Kapitel: Schule, erster Job, Krise, Mentor—mit Gesicht und Zitat echter Teilnehmer.", "Narrative Strategie der Jugendstiftungs-Kampagne", "Video, Social, Landing und Spendenflow als ein Weg: Person, Kontext, Handlung. Warm, nicht infantil.", "Lokale Medien adaptierten Assets—Reichweite mit Intimität. Wiedererkennbares Kampagnenformat.", "Reichweite der Jugendstiftungs-Kampagne"),
    ("Une fondation jeunesse devait percer la lassitude caritative—sans pathos ni chiffres froids. Les jeunes comme héros, pas comme bénéficiaires de slide.", "Une voix qui a un avenir", "Au-delà d'un pic de dons : modèles et partenaires médias pour chaque saison.", "Chapitres : école, premier emploi, crise, mentor—visage et citation de participants.", "Stratégie narrative de la campagne sociale de la fondation jeunesse", "Vidéo, carrousels, landing et don : rencontrer, comprendre, agir. Visuel chaleureux, pas enfantin.", "Médias locaux ont adapté les assets—portée sans perdre l'intimité. Format reconnaissable.", "Portée de la campagne de la fondation jeunesse"),
    ("Фонду поддержки молодёжи нужна была кампания сквозь усталость от благотворительности — без пафоса и холодной статистики. Молодые люди — герои истории.", "Голос с будущим", "Кампания вышла за разовый пик пожертвований — шаблоны и медиапартнёры на сезоны вперёд.", "Главы: школа, первая работа, кризис, наставник — лицо и цитата участника.", "Нарративная стратегия социальной кампании фонда", "Видео, карусели, лендинг и донат: человек, контекст, действие. Тёплый визуал без инфантильности.", "Локальные СМИ адаптировали материалы — охват без потери близости.", "Охват кампании фонда в медиа и соцсетях"),
    ("Uma fundação de apoio à juventude precisava de uma campanha que rompesse a fadiga solidária—sem melodrama nem estatísticas frias. Jovens como heróis da história.", "Uma voz com futuro", "Além de um pico de doações: modelos e parceiros de media em cada temporada.", "Capítulos: escola, primeiro emprego, crise, mentor—rosto e citação de participantes.", "Estratégia narrativa da campanha social da fundação", "Vídeo, carrosséis, landing e doação: conhecer, compreender, agir. Visual caloroso, não infantil.", "Media locais adaptaram assets—alcance com intimidade. Formato reconhecível.", "Alcance da campanha da fundação em media e social"),
)

PROJECTS["callisto"] = L(
    ("The Callisto Protocol to horror science fiction, który miał zdefiniować nową markę Striking Distance Studios obok legendy Dead Space. Premiera gry wymagała kampanii równie niepokojącej jak sama rozgrywka — i jednocześnie czytelnej dla graczy na wielu platformach. Stawką było zaufanie hardcorowej społeczności survival horroru.", "Strach jako obietnica marki", "Callisto weszło do kanonu gier grozy jako produkt, ale i jako case study: jak wprowadzić nowego IP na tłoczny rynek bez kompromisu w jakości narracji marketingowej.", "Rozdziały kampanii odpowiadały aktom gry: izolacja, mutacja, ucieczka. Strategia budowała lore stopniowo — teaser, gameplay, partnerstwa influencerów — tak aby każdy touchpoint pogłębiał ten sam klimat, zamiast zdradzać wszystko naraz.", "Strategia launchowa The Callisto Protocol — Striking Distance Studios", "Trailery, interaktywne zwiastuny, eventy dla prasy i personalizowane assety na platformy digital sprawiły, że gracz czuł ciężar świata Callisto jeszcze przed startem gry. Dźwięk i typografia były spójne z UI gry.", "Kampania objęła rynki Ameryki Północnej, Europy i Azji z lokalizowanymi materiałami ratingowymi i partnerstwami retail. Globalny launch utrzymał jedną wizję kreatywną na wszystkich terytoriach.", "Globalna kampania The Callisto Protocol na rynkach międzynarodowych"),
    ("The Callisto Protocol is sci-fi horror meant to define Striking Distance Studios beside the Dead Space legacy. Launch needed a campaign as unsettling as gameplay—and clear across platforms. Trust of the survival-horror community was at stake.", "Fear as a brand promise", "Callisto joined the horror canon as product and case study: launching new IP in a crowded market without compromising narrative quality.", "Chapters mirrored game acts: isolation, mutation, escape. Lore built gradually—teasers, gameplay, influencers—each touchpoint deepening mood, not spoiling all at once.", "Launch strategy for The Callisto Protocol, Striking Distance Studios", "Trailers, interactive teasers, press events, and tailored digital assets made players feel Callisto's weight before day one. Sound and type matched in-game UI.", "North America, Europe, and Asia with localized rating assets and retail partners—one creative vision globally.", "Global marketing for The Callisto Protocol"),
    ("The Callisto Protocol sollte Striking Distance neben Dead Space definieren. Launch-Kampagne so beunruhigend wie das Gameplay—klar auf allen Plattformen.", "Angst als Markenversprechen", "Callisto als Produkt und Case Study: neues IP ohne Kompromiss in der Marketing-Narrative.", "Kapitel wie Spielakte: Isolation, Mutation, Flucht. Lore schrittweise—Teaser, Gameplay, Influencer.", "Launch-Strategie The Callisto Protocol", "Trailer, interaktive Teaser, Presseevents, Digital-Assets—Spieler spürten Callisto vor Tag eins.", "NA, Europa, Asien—lokalisierte Ratings, eine globale Vision.", "Globale Kampagne The Callisto Protocol"),
    ("The Callisto Protocol devait définir Striking Distance aux côtés de Dead Space. Une campagne aussi inquiétante que le jeu—lisible sur toutes les plateformes.", "La peur comme promesse de marque", "Callisto dans le canon horrifique—nouvel IP sans compromis narratif.", "Chapitres miroir des actes : isolement, mutation, fuite. Lore progressif—teasers, gameplay, influenceurs.", "Stratégie de lancement The Callisto Protocol", "Trailers, teasers interactifs, presse, assets digitaux—le poids de Callisto avant le jour J.", "Amérique du Nord, Europe, Asie—une vision créative mondiale.", "Campagne mondiale The Callisto Protocol"),
    ("The Callisto Protocol — sci-fi horror, призванный определить Striking Distance рядом с наследием Dead Space. Кампания должна была быть такой же тревожной, как геймплей.", "Страх как обещание бренда", "Callisto в каноне хоррора — кейс запуска нового IP без компромиссов в нарративе.", "Главы как акты игры: изоляция, мутация, побег. Лор постепенно — тизеры, геймплей, инфлюенсеры.", "Стратегия запуска The Callisto Protocol", "Трейлеры, интерактивные тизеры, ивенты для прессы — вес мира Callisto до релиза.", "Северная Америка, Европа, Азия — одна креативная vision.", "Глобальная кампания The Callisto Protocol"),
    ("The Callisto Protocol é horror sci-fi para definir a Striking Distance ao lado de Dead Space. Campanha tão inquietante quanto o jogo—clara em todas as plataformas.", "Medo como promessa de marca", "Callisto no cânone do horror—novo IP sem comprometer a narrativa de marketing.", "Capítulos espelham atos: isolamento, mutação, fuga. Lore gradual—teasers, gameplay, influencers.", "Estratégia de lançamento The Callisto Protocol", "Trailers, teasers interativos, imprensa, assets digitais—peso de Callisto antes do dia um.", "América do Norte, Europa, Ásia—uma visão criativa global.", "Campanha global The Callisto Protocol"),
)

PROJECTS["hogwarts"] = L(
    ("Hogwarts Legacy to jedna z najbardziej oczekiwanych premier w historii gier akcji RPG — z ogromną społecznością fanów i równie wielką presją na każdy fragment komunikacji. WB Games i Avalanche potrzebowały kampanii, która uszanuje mit Hogwartu, a jednocześnie zaprezentuje nową, interaktywną wizję świata czarodziejów.", "Mit otwiera drzwi", "Hogwarts Legacy pokazało, że globalne IP można wprowadzić na nową generację konsol bez rozmycia magii — gdy strategia, produkcja i dystrybucja digital idą w jednym rytmie.", "Podzieliliśmy narrację na rozdziały odkrywania: Hogwart, zaklęcia, stworzenia, wybory moralne gracza. Każdy akt kampanii dokładał nową warstwę świata, respektując kanon i budując ciekawość bez spoilerów fabularnych.", "Strategia marketingowa Hogwarts Legacy — WB Games i Avalanche", "State of Play, materiały dla twórców, kampanie w social i personalizacja sklepów platformowych stworzyły wrażenie, że gracz już nosi szatę ucznia. Estetyka oświetlenia i dźwięku była przedłużeniem trailera w każdym formacie.", "Premiera objęła dziesiątki rynków z zsynchronizowanym beat-em komunikacyjnym i lokalnymi eventami dla mediów. Hogwarts Legacy stało się wzorcem launchu dla dużych licencji w erze streamingowej.", "Globalny launch Hogwarts Legacy w kanałach digital i retail"),
    ("Hogwarts Legacy was among the most anticipated action-RPG launches—with huge fan pressure on every touchpoint. WB Games and Avalanche needed a campaign honoring the Hogwarts myth while presenting a new interactive wizarding world.", "The myth opens the door", "Hogwarts Legacy showed global IP can reach a new console generation without diluting magic—when strategy, production, and digital move together.", "Chapters of discovery: Hogwarts, spells, creatures, player morality—each act adding world layers without plot spoilers.", "Marketing strategy for Hogwarts Legacy, WB Games and Avalanche", "State of Play, creator kits, social, and store personalization made players feel like students before launch.", "Dozens of markets, synchronized beats, local press events—a launch benchmark for licensed games in streaming era.", "Global Hogwarts Legacy launch across digital and retail"),
    ("Hogwarts Legacy—eines der erwartetsten Action-RPGs. Kampagne ehrt den Mythos und zeigt eine neue interaktive Zaubererwelt.", "Der Mythos öffnet die Tür", "Globales IP auf neuer Konsolengeneration—Magie bleibt, wenn Strategie und Digital synchron laufen.", "Kapitel der Entdeckung: Hogwarts, Zauber, Kreaturen, Moral—ohne Spoiler.", "Marketingstrategie Hogwarts Legacy", "State of Play, Creator, Social, Store-Personalisierung—Schülergefühl vor Launch.", "Dutzende Märkte, synchronisierte Beats—Benchmark für Lizenz-Launches.", "Globaler Launch Hogwarts Legacy"),
    ("Hogwarts Legacy—l'une des sorties RPG les plus attendues. Campagne honorant le mythe tout en présentant un monde sorcier interactif.", "Le mythe ouvre la porte", "Un IP mondial sur une nouvelle génération sans diluer la magie—stratégie et digital alignés.", "Chapitres de découverte : Poudlard, sorts, créatures, morale—sans spoilers.", "Stratégie marketing Hogwarts Legacy", "State of Play, créateurs, social, stores—sentir l'uniforme avant le lancement.", "Des dizaines de marchés, rythme synchronisé—référence des licences.", "Lancement mondial Hogwarts Legacy"),
    ("Hogwarts Legacy — одна из самых ожидаемых RPG-премьер. Кампания должна была почтить миф Хогвартса и показать новый интерактивный мир.", "Миф открывает дверь", "Глобальное IP на новом поколении консолей без размывания магии — при синхронной стратегии и digital.", "Главы открытия: Хогвартс, заклинания, существа, мораль игрока — без спойлеров.", "Маркетинговая стратегия Hogwarts Legacy", "State of Play, креаторы, social, персонализация сторов — ощущение школьной формы до релиза.", "Десятки рынков, синхронный ритм — эталон лицензионных запусков.", "Глобальный launch Hogwarts Legacy"),
    ("Hogwarts Legacy—um dos lançamentos RPG mais aguardados. Campanha que honra o mito e apresenta um novo mundo bruxo interativo.", "O mito abre a porta", "IP global numa nova geração de consolas sem diluir a magia—estratégia e digital alinhados.", "Capítulos de descoberta: Hogwarts, feitiços, criaturas, moral—sem spoilers.", "Estratégia de marketing Hogwarts Legacy", "State of Play, criadores, social, lojas—sentir o uniforme antes do lançamento.", "Dezenas de mercados, batidas sincronizadas—referência de licenças.", "Lançamento global Hogwarts Legacy"),
)

PROJECTS["linkbuds"] = L(
    ("Sony LinkBuds wchodziły na rynek w momencie, gdy słuchawki true wireless były już normą — a wyzwaniem stało się zaprojektowanie produktu, który słychać i czuć inaczej. Otwarta konstrukcja miała łączyć muzykę z otoczeniem, nie kompromitując jakości marki Sony. Kampania musiała wytłumaczyć innowację w sekundę scrolla.", "Słuchaj świata dalej", "LinkBuds utrwaliły pozycję Sony jako lidera audio, który nie kopiuje formy, lecz proponuje własną filozofię noszenia dźwięku — z kampanią, która brzmi lekko, ale jest precyzyjna technologicznie.", "Strategia opierała się na trzech rozdziałach: wolność ruchu, świadomość otoczenia, sygnatura dźwięku Sony. Każdy rozdział miał własną metaforę wizualną — miasto, biuro, bieg — ale ten sam produkt w centrum kadru.", "Strategia produktowa i kreatywna Sony LinkBuds", "Krótkie filmy produktowe, demo audio w digital i materiały dla sprzedawców detalicznych pomogły klientowi „usłyszeć” różnicę bez wizyty w sklepie. UX komunikacji był równie czysty jak industrial design słuchawek.", "Kampania wystartowała równolegle w kluczowych regionach Azji, Europy i Ameryki Północnej z lokalnymi ambasadorami lifestyle. LinkBuds zyskały rozpoznawalność jako kategoria „open audio” w portfolio Sony.", "Globalna kampania Sony LinkBuds w kanałach digital i retail"),
    ("Sony LinkBuds launched when true wireless was already the norm—the challenge was a product that sounds and feels different. Open-ring design blends music with surroundings without compromising Sony quality. The campaign had to explain innovation in a scroll's second.", "Keep listening to the world", "LinkBuds reinforced Sony audio leadership with its own philosophy of wearing sound—light campaign, precise tech story.", "Three chapters: freedom of movement, awareness, Sony signature sound—city, office, run metaphors, product centered.", "Product and creative strategy for Sony LinkBuds", "Short films, digital audio demos, and retail sell-in helped customers hear the difference without a store visit.", "Parallel launch across Asia, Europe, and North America with lifestyle ambassadors—'open audio' in Sony's portfolio.", "Global Sony LinkBuds campaign in digital and retail"),
    ("Sony LinkBuds im überfüllten True-Wireless-Markt—ein Produkt, das anders klingt und sich anders anfühlt. Offenes Design verbindet Musik und Umgebung.", "Weiter zur Welt hören", "Sony als Audio-Führer mit eigener Open-Audio-Philosophie.", "Drei Kapitel: Bewegung, Umgebung, Sony-Sound—Stadt, Büro, Lauf.", "Produkt- und Kreativstrategie Sony LinkBuds", "Kurzfilme, Audio-Demos, Retail—Unterschied hören ohne Ladenbesuch.", "Parallel in Asien, Europa, Nordamerika—Open Audio etabliert.", "Globale LinkBuds-Kampagne"),
    ("Sony LinkBuds dans un marché true wireless saturé—un produit qui sonne et se ressent autrement. Design ouvert : musique et environnement.", "Continuer d'écouter le monde", "Sony leader audio avec sa philosophie open audio.", "Trois chapitres : mouvement, environnement, signature Sony—ville, bureau, course.", "Stratégie produit et créative Sony LinkBuds", "Films courts, démos audio, retail—entendre la différence sans magasin.", "Lancement parallèle en Asie, Europe, Amérique du Nord.", "Campagne mondiale Sony LinkBuds"),
    ("Sony LinkBuds выходили, когда true wireless уже был нормой — нужен продукт, который звучит и ощущается иначе. Открытая конструкция соединяет музыку с окружением.", "Слушай мир дальше", "Sony укрепила лидерство в audio собственной философией open audio.", "Три главы: движение, осознанность окружения, фирменный звук Sony.", "Продуктовая и креативная стратегия Sony LinkBuds", "Короткие ролики, audio-демо, retail — услышать разницу без визита в магазин.", "Параллельный старт в Азии, Европе и Северной Америке.", "Глобальная кампания Sony LinkBuds"),
    ("Sony LinkBuds num mercado true wireless saturado—um produto que soa e se sente diferente. Design aberto une música e ambiente.", "Continue a ouvir o mundo", "Sony reforçou a liderança em áudio com filosofia open audio.", "Três capítulos: movimento, ambiente, som Sony—cidade, escritório, corrida.", "Estratégia de produto e criativa Sony LinkBuds", "Filmes curtos, demos de áudio, retail—ouvir a diferença sem loja.", "Lançamento paralelo na Ásia, Europa e América do Norte.", "Campanha global Sony LinkBuds"),
)

PROJECTS["loto"] = L(
    ("Loto-Québec modernizowało relację z graczami przez aplikację mobilną, która musiała łączyć bezpieczeństwo, regulacje i przyjemność z codziennego użytkowania. W Quebecu loteria to instytucja — każda zmiana interfejsu to także zmiana nawyku. Projekt wymagał zaufania użytkowników w każdym ekranie.", "Gra w nowym rytmie", "Aplikacja mobilna Loto-Québec stała się standardem wygodnej, odpowiedzialnej gry — i dowodem, że sektor regulowany może być równie nowoczesny wizualnie jak najlepsze fintechy.", "Rozdziały strategii odpowiadały etapom podróży: odkrycie, rejestracja, gra, odpowiedzialność. Zdefiniowaliśmy ton głosu i architekturę informacji tak, aby instytucjonalna wiarygodność szła w parze z lekkością mobile-first.", "Strategia UX i marki aplikacji mobilnej Loto-Québec", "Projekt interfejsu, mikrocopy, onboarding i powiadomienia zaprojektowaliśmy jako jeden system — z testami użyteczności i scenariuszami dostępności. Każdy klik miał prowadzić użytkownika bez tarcia, ale z pełną przejrzystością zasad.", "Choć produkt jest głęboko zakorzeniony w Quebecu, rozwiązania design systemu i komunikacji odpowiedzialnej grze zostały zaprezentowane na konferencjach branżowych jako wzorzec dla operatorów na innych rynkach.", "Aplikacja mobilna Loto-Québec — zasięg i adopcja użytkowników"),
    ("Loto-Québec modernized player relationships via a mobile app balancing security, regulation, and everyday ease. In Quebec, lottery is an institution—every UI change is a habit change. Trust on every screen was required.", "Play in a new rhythm", "The app became a standard for convenient, responsible play—proof regulated sectors can look as modern as top fintechs.", "Strategy chapters mapped discovery, registration, play, and responsibility—institutional credibility with mobile-first lightness.", "UX and brand strategy for the Loto-Québec mobile app", "UI, microcopy, onboarding, and notifications as one system—with usability and accessibility testing. Transparent rules, low friction.", "Quebec-rooted, yet the design system and responsible-play comms became a conference benchmark for other operators.", "Loto-Québec mobile app reach and adoption"),
    ("Loto-Québec modernisierte die Spielerbeziehung per App—Sicherheit, Regulierung und Alltagstauglichkeit. Lotterie als Institution: Vertrauen auf jedem Screen.", "Spielen im neuen Rhythmus", "Standard für bequemes, verantwortungsvolles Spiel—regulierte Branche so modern wie Fintech.", "Kapitel: Entdeckung, Registrierung, Spiel, Verantwortung—Glaubwürdigkeit und Mobile-First.", "UX- und Markenstrategie der Loto-Québec-App", "UI, Microcopy, Onboarding, Notifications als System—Usability und Barrierefreiheit.", "Designsystem als Branchenvorbild auf Konferenzen.", "Reichweite und Adoption der Loto-Québec-App"),
    ("Loto-Québec a modernisé la relation joueur via une app mobile—sécurité, régulation et usage quotidien. Loterie institution au Québec : confiance à chaque écran.", "Jouer sur un nouveau rythme", "Standard de jeu pratique et responsable—secteur régulé aussi moderne que la fintech.", "Chapitres : découverte, inscription, jeu, responsabilité—crédibilité institutionnelle et mobile-first.", "Stratégie UX et marque de l'app Loto-Québec", "UI, microcopy, onboarding, notifications—un système testé accessibilité.", "Design system présenté en conférences comme modèle.", "Portée et adoption de l'app Loto-Québec"),
    ("Loto-Québec модернизировало отношения с игроками через мобильное приложение — безопасность, регуляция и удобство. В Квебеке лотерея — институт; доверие на каждом экране.", "Игра в новом ритме", "Приложение стало стандартом ответственной игры — регулируемый сектор может выглядеть как fintech.", "Главы пути: знакомство, регистрация, игра, ответственность — институциональная надёжность и mobile-first.", "UX- и бренд-стратегия приложения Loto-Québec", "UI, микрокопи, онбординг, уведомления — единая система с тестами доступности.", "Design system как отраслевой эталон на конференциях.", "Охват и adoption приложения Loto-Québec"),
    ("A Loto-Québec modernizou a relação com jogadores via app mobile—segurança, regulação e uso diário. Lotaria como instituição no Quebec: confiança em cada ecrã.", "Jogar num novo ritmo", "A app tornou-se padrão de jogo conveniente e responsável—setor regulado tão moderno quanto fintech.", "Capítulos: descoberta, registo, jogo, responsabilidade—credibilidade institucional e mobile-first.", "Estratégia UX e marca da app Loto-Québec", "UI, microcopy, onboarding, notificações—sistema com testes de acessibilidade.", "Design system como referência em conferências.", "Alcance e adoção da app Loto-Québec"),
)

PROJECTS["canadiens"] = L(
    ("Montreal Canadiens to nie tylko klub NHL — to instytucja kultury Quebecu. Kampania The Original One miała oddać dziedzictwo bez muzealnego patosu i zaprosić nowe pokolenie kibiców do poczucia własności tej historii. Wyzwaniem było połączenie szacunku dla tradycji z energią współczesnego sportu marketingowego.", "Dziedzictwo w ruchu", "The Original One przypomniało, że najsilniejsze marki sportowe nie żyją w przeszłości — one ją ciągną na lodzie, w mieście i w każdym kolejnym sezonie.", "Historię Canadiens opowiedzieliśmy rozdziałami: pierwsze dekady, ikony, współczesny skład, społeczność kibiców. Strategia łączyła archiwalia z nowym materiałem filmowym, budując most między pokoleniami.", "Strategia kampanii The Original One — Montreal Canadiens", "Spot hero, serie social, merchandise i eventy w Bell Centre tworzyły jedno doświadczenie kibica — od emocji na trybunach po personalizowany content w aplikacji klubu. Każdy format niósł ten sam szlachecki rytm marki.", "Choć serce kampanii bije w Montrealu, narracja trafiła do fanów NHL w USA i Europie dzięki partnerstwom streamingowym i międzynarodowym mediom sportowym. The Original One wzmocniło pozycję Canadiens jako marki eksportowej kultury hokeja.", "Globalny zasięg kampanii Montreal Canadiens The Original One"),
    ("The Montreal Canadiens are a Quebec cultural institution—not only an NHL club. The Original One had to honor heritage without museum dust and invite a new generation to own that history—tradition plus modern sports marketing energy.", "A legacy in motion", "The strongest sports brands don't live in the past—they pull it onto the ice, into the city, every season.", "Chapters: early decades, icons, today's roster, fan community—archives plus new film bridging generations.", "Strategy for The Original One campaign, Montreal Canadiens", "Hero film, social, merch, and Bell Centre events as one fan journey—stands to club app personalization.", "Montreal's heart, but narrative reached NHL fans in the U.S. and Europe via streaming and sports media.", "Global reach of Montreal Canadiens The Original One"),
    ("Die Montreal Canadiens—Kulturinstitution Québecs. The Original One: Erbe ohne Museumsstaub, neue Generation als Eigentümer der Geschichte.", "Erbe in Bewegung", "Starke Sportmarken leben nicht in der Vergangenheit—sie ziehen sie aufs Eis und in die Stadt.", "Kapitel: Jahrzehnte, Ikonen, Kader, Fans—Archiv und neuer Film.", "Strategie The Original One, Montreal Canadiens", "Hero, Social, Merch, Bell Centre—eine Fan-Journey.", "Montreal plus NHL-Fans in USA und Europa via Streaming.", "Globale Reichweite The Original One"),
    ("Les Canadiens de Montréal—institution culturelle du Québec. The Original One : héritage sans poussière de musée, nouvelle génération propriétaire de l'histoire.", "Un héritage en mouvement", "Les grandes marques sportives tirent le passé sur la glace et dans la ville.", "Chapitres : décennies, icônes, effectif, communauté—archives et film neuf.", "Stratégie The Original One, Canadiens de Montréal", "Film hero, social, merch, Bell Centre—un parcours fan.", "Montréal et fans NHL aux États-Unis et en Europe.", "Portée mondiale The Original One"),
    ("Montreal Canadiens — не только клуб NHL, но и культурный институт Квебека. The Original One: наследие без музейного пыли, новое поколение как хозяева истории.", "Наследие в движении", "Сильнейшие спортивные бренды тянут прошлое на лёд и в город каждый сезон.", "Главы: десятилетия, иконы, состав, фан-сообщество — архив и новый фильм.", "Стратегия кампании The Original One — Montreal Canadiens", "Hero-ролик, social, мерч, Bell Centre — путь фаната.", "Монреаль и фаны NHL в США и Европе через стриминг.", "Глобальный охват The Original One"),
    ("Os Montreal Canadiens são instituição cultural do Quebec. The Original One: herança sem pó de museu, nova geração dona da história.", "Um legado em movimento", "As marcas desportivas mais fortes puxam o passado para o gelo e para a cidade.", "Capítulos: décadas, ícones, plantel, comunidade—arquivo e filme novo.", "Estratégia The Original One, Montreal Canadiens", "Filme hero, social, merch, Bell Centre—jornada do adepto.", "Montreal e fãs NHL nos EUA e Europa via streaming.", "Alcance global The Original One"),
)

PROJECTS["dragCreative"] = L(
    ("Sasha Velour to artystka, która przesuwa granice drag, sztuk wizualnych i przedsiębiorczości kreatywnej. Współpraca miała pokazać, że tożsamość i biznes nie są przeciwieństwami — że można budować markę osobistą z pozycji autentyczności, nie konformizmu. Projekt wymagał wrażliwości na społeczność LGBTQ+ i język mainstreamowych mediów.", "Tożsamość jako scena", "Kampania utrwaliła Sasha Velour jako przykład kreatywnej ekonomii: art, który zarabia, nie zdradzając wartości, i biznes, który nie wstydzi się teatralności.", "Rozdziały strategii dotyczyły sztuki, edukacji i monetyzacji: od show na scenie po kursy i współprace z markami. Każdy rozdział miał własny ton, ale wspólną zasadę — szacunek do widza i do historii drag.", "Strategia marki osobistej Sasha Velour — kreatywność i biznes", "Wideo, wystawy, social i landing ofertowy zaprojektowaliśmy jako ciągłe przedstawienie: widz wchodzi w kulisy twórczości i wychodzi z konkretnym wezwaniem — kup bilet, dołącz do warsztatu, wesprzyj projekt.", "Treści obiegły festiwale, platformy streamingowe i media kultury pop na kilku kontynentach. Projekt otworzył dialog o roli drag w marketingu marek szukających prawdziwej inkluzywności, nie tylko gestu w Pride month.", "Międzynarodowy zasięg projektu Sasha Velour"),
    ("Sasha Velour pushes boundaries of drag, visual art, and creative entrepreneurship. The collaboration showed identity and business aren't opposites—a personal brand from authenticity, not conformity—with LGBTQ+ sensitivity and mainstream media fluency.", "Identity as the stage", "The campaign anchored Sasha as creative-economy proof: art that earns without betraying values; business unafraid of theatricality.", "Chapters on art, education, monetization—from stage to courses and brand collabs—respect for audience and drag history.", "Personal brand strategy for Sasha Velour—creativity and business", "Video, exhibitions, social, and offer landing as one performance: backstage in, ticket or workshop out.", "Festivals, streaming, and pop culture media across continents—dialogue on drag's role beyond Pride-month gestures.", "International reach of the Sasha Velour project"),
    ("Sasha Velour erweitert Grenzen von Drag, Kunst und kreativem Business—Identität und Commerce als Partner, nicht Gegner.", "Identität als Bühne", "Kreative Ökonomie: Kunst verdient, Werte bleiben; Business ohne Scheu vor Theater.", "Kapitel Kunst, Bildung, Monetarisierung—Respekt für Publikum und Drag-Geschichte.", "Personal-Brand-Strategie Sasha Velour", "Video, Ausstellungen, Social, Landing als eine Performance.", "Festivals und Streaming weltweit—Drag jenseits des Pride-Gestus.", "Internationale Reichweite Sasha Velour"),
    ("Sasha Velour repousse les frontières du drag, de l'art visuel et de l'entrepreneuriat créatif—identité et business alliés.", "L'identité comme scène", "Économie créative : l'art qui paie sans trahir les valeurs.", "Chapitres art, éducation, monétisation—respect du public et de l'histoire drag.", "Stratégie de marque personnelle Sasha Velour", "Vidéo, expositions, social, landing comme spectacle continu.", "Festivals et streaming sur plusieurs continents.", "Portée internationale du projet Sasha Velour"),
    ("Sasha Velour расширяет границы drag, визуального искусства и креативного бизнеса — идентичность и коммерция не противоположности.", "Идентичность как сцена", "Креативная экономика: искусство, которое зарабатывает, не предавая ценности.", "Главы: искусство, образование, монетизация — уважение к аудитории и истории drag.", "Стратегия личного бренда Sasha Velour", "Видео, выставки, social и лендинг как непрерывное представление.", "Фестивали и стриминг на нескольких континентах.", "Международный охват проекта Sasha Velour"),
    ("Sasha Velour expande fronteiras do drag, arte visual e empreendedorismo criativo—identidade e negócio como aliados.", "Identidade como palco", "Economia criativa: arte que rende sem trair valores.", "Capítulos arte, educação, monetização—respeito pelo público e pela história do drag.", "Estratégia de marca pessoal Sasha Velour", "Vídeo, exposições, social e landing como espetáculo contínuo.", "Festivais e streaming em vários continentes.", "Alcance internacional do projeto Sasha Velour"),
)

PROJECTS["resortsWorld"] = L(
    ("Resorts World Las Vegas stawiało na doświadczenie gościa, które łączy hospitality, rozrywkę i technologię — a GLOW | Digital Kitchen miało być wizytówką tej obietnicy w świecie digital. W mieście, gdzie każdy resort krzyczy neonem, wyzwaniem było stworzyć język wizualny równie sensoryczny jak pobyt w hotelu.", "Światło, które zaprasza", "GLOW stało się cyfrowym prologiem Resorts World: miejscem, gdzie gość czuje klimat Las Vegas jeszcze przed rezerwacją pokoju — i templatem dla kolejnych aktywacji Digital Kitchen.", "Strategia rozbiła resort na rozdziały zmysłów: smak, muzyka, światło, gra. Digital Kitchen miała być sceną, na której te rozdziały spotykają się w jednym płynnym UI — bez chaosu typowego dla Vegas.", "Strategia GLOW Digital Kitchen — Resorts World Las Vegas", "Interaktywne menu, rezerwacje, live content i personalizowane rekomendacje zaprojektowaliśmy jako jeden ekosystem. Animacja, dźwięk i copy prowadziły użytkownika jak concierge — szybko, z klasą, z nutą show.", "Kampania digital wspierała międzynarodowych gości planujących podróż do Vegas — w wielu językach i kanałach płatnych. GLOW zwiększyło rozpoznawalność Resorts World poza Strip i wzmocniło metryki rezerwacji bezpośrednich.", "Globalny zasięg kampanii GLOW Resorts World Las Vegas"),
    ("Resorts World Las Vegas bets on guest experience blending hospitality, entertainment, and tech—GLOW | Digital Kitchen was the digital showcase. In neon-saturated Vegas, we needed a visual language as sensory as the stay.", "Light that invites", "GLOW became Resorts World's digital prologue—Vegas mood before booking—and a template for future Digital Kitchen activations.", "Chapters of the senses: taste, music, light, play—one fluid UI without typical Vegas chaos.", "GLOW Digital Kitchen strategy, Resorts World Las Vegas", "Menus, reservations, live content, and recommendations as one ecosystem—concierge-like motion, sound, and copy.", "Digital campaigns for international Vegas planners—multilingual paid channels, awareness beyond the Strip, stronger direct bookings.", "Global reach of GLOW, Resorts World Las Vegas"),
    ("Resorts World Las Vegas verbindet Hospitality, Entertainment und Tech—GLOW | Digital Kitchen als digitale Visitenkarte. In Neon-Vegas eine Sprache so sensorisch wie der Aufenthalt.", "Licht, das einlädt", "GLOW als digitaler Prolog vor der Buchung—Template für Digital Kitchen.", "Kapitel der Sinne: Geschmack, Musik, Licht, Spiel—ein flüssiges UI.", "GLOW Digital Kitchen Strategie, Resorts World Las Vegas", "Menüs, Reservierungen, Live-Content als Ökosystem—Concierge-Flow.", "Kampagnen für internationale Gäste—Reichweite jenseits des Strip.", "Globale Reichweite GLOW"),
    ("Resorts World Las Vegas allie hospitalité, divertissement et tech—GLOW | Digital Kitchen comme vitrine digitale. À Vegas, un langage visuel aussi sensoriel que le séjour.", "Une lumière qui invite", "GLOW comme prologue digital avant réservation—modèle pour Digital Kitchen.", "Chapitres des sens : goût, musique, lumière, jeu—une UI fluide.", "Stratégie GLOW Digital Kitchen, Resorts World Las Vegas", "Menus, réservations, live—écosystème type concierge.", "Campagnes pour voyageurs internationaux—au-delà du Strip.", "Portée mondiale de GLOW"),
    ("Resorts World Las Vegas строит опыт гостя на hospitality, развлечениях и технологиях — GLOW | Digital Kitchen как digital-витрина. В неоновом Vegas нужен визуальный язык как само пребывание.", "Свет, который приглашает", "GLOW как digital-пролог до бронирования — шаблон для Digital Kitchen.", "Главы чувств: вкус, музыка, свет, игра — единый плавный UI.", "Стратегия GLOW Digital Kitchen — Resorts World Las Vegas", "Меню, бронирование, live-контент — экосистема как concierge.", "Кампании для международных гостей — узнаваемость за пределами Strip.", "Глобальный охват GLOW"),
    ("Resorts World Las Vegas aposta na experiência do hóspede—GLOW | Digital Kitchen como vitrine digital. Em Vegas, uma linguagem visual tão sensorial quanto a estadia.", "Luz que convida", "GLOW como prólogo digital antes da reserva—modelo para Digital Kitchen.", "Capítulos dos sentidos: sabor, música, luz, jogo—UI fluida.", "Estratégia GLOW Digital Kitchen, Resorts World Las Vegas", "Menus, reservas, live content—ecossistema tipo concierge.", "Campanhas para hóspedes internacionais—além do Strip.", "Alcance global de GLOW"),
)

FIELD_KEYS = ("intro", "outroTitle", "outro", "block1.body", "block1.imageAlt", "block2.body", "block3.body", "block3.imageAlt")
BLOCK_KEYS = ("block1.title", "block2.title", "block3.title")

def project_keys(project_id: str) -> dict[str, dict[str, str]]:
    by_locale: dict[str, dict[str, str]] = {loc: {} for loc in LOCALES}
    data = PROJECTS[project_id]
    prefix = f"marketing.partnerships.projects.{project_id}.detail."
    for loc in LOCALES:
        fields = data[loc]
        for key, value in zip(FIELD_KEYS, fields):
            by_locale[loc][prefix + key] = value
        for key, value in zip(BLOCK_KEYS, BLOCK_TITLES[loc]):
            by_locale[loc][prefix + key] = value
    return by_locale

def main():
    merged = {loc: dict(SHARED[loc]) for loc in LOCALES}
    for pid in PROJECTS:
        flat = project_keys(pid)
        for loc in LOCALES:
            merged[loc].update(flat[loc])
    OUT.write_text(json.dumps(merged, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"Wrote {OUT} with {len(merged)} locales, {len(merged['pl'])} keys per pl locale")

if __name__ == "__main__":
    main()
