"""create campaign table

Revision ID: 057792d866ca
Revises: a7dfc1bc3451
Create Date: 2026-05-13 20:16:56.396005

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '057792d866ca'
down_revision = 'a7dfc1bc3451'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
