"""create_bank_table

Revision ID: 36fe52c30d08
Revises: b2f4a8e1d0cc
Create Date: 2026-06-05 12:17:28.135955

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '36fe52c30d08'
down_revision = 'b2f4a8e1d0cc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('bank_address', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('account_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('iban', sqlmodel.sql.sqltypes.AutoString(length=34), nullable=False),
    sa.Column('sepa', sa.Boolean(), nullable=False),
    sa.Column('swift', sqlmodel.sql.sqltypes.AutoString(length=11), nullable=False),
    sa.Column('company_address', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('transfer_title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('bank_description', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('bank_logo', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bank')
    # ### end Alembic commands ###
