"""create_account_table

Revision ID: 5ab4db29769f
Revises: afb8a0103c03
Create Date: 2026-06-05 14:47:52.144394

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '5ab4db29769f'
down_revision = 'afb8a0103c03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('account_type', sa.Enum('FUNDAMENT', 'ACCELERATOR', 'STRATEGY', 'ALPHA', 'PROTECTOR', 'DOMINION', name='accounttype', native_enum=False, length=64), nullable=False),
    sa.Column('participation', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('available_balance', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('total_deposit', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('total_withdraw', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('custom_campaigns', sa.Boolean(), nullable=False),
    sa.Column('card_payments', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_user_id'), 'account', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_account_user_id'), table_name='account')
    op.drop_table('account')
    # ### end Alembic commands ###
