"""create campaign table

Revision ID: a7dfc1bc3451
Revises: e7d8f9a01bc2
Create Date: 2026-05-13 19:49:19.519277

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a7dfc1bc3451'
down_revision = 'e7d8f9a01bc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
