"""change_bank_sepa_to_string

Revision ID: afb8a0103c03
Revises: 36fe52c30d08
Create Date: 2026-06-05 13:21:32.184241

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'afb8a0103c03'
down_revision = '36fe52c30d08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bank', 'sepa',
               existing_type=sa.BOOLEAN(),
               type_=sqlmodel.sql.sqltypes.AutoString(length=64),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bank', 'sepa',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=64),
               type_=sa.BOOLEAN(),
               existing_nullable=False)
    # ### end Alembic commands ###
