"""update campaign table

Revision ID: cde6ee011e6c
Revises: 37575cddeaf0
Create Date: 2026-05-21 12:04:55.009011

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'cde6ee011e6c'
down_revision = '37575cddeaf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
