"""update user table 2

Revision ID: d180f61f1a81
Revises: a70a1aa7b0da
Create Date: 2026-05-07 18:06:44.759855

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd180f61f1a81'
down_revision = 'a70a1aa7b0da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
