from app.activation_email_copy import normalize_activation_language

PASSWORD_RECOVERY_EMAIL_COPY: dict[str, dict[str, str]] = {
    "pl": {
        "subject": "SidLee Media - odzyskiwanie hasła",
        "title": "Odzyskiwanie hasła",
        "greeting": "Dzień dobry,",
        "intro": "otrzymaliśmy prośbę o odzyskanie dostępu do Twojego konta na naszej platformie SidLee Media.",
        "lead": "Poniżej znajdziesz jednorazowe hasło umożliwiające zalogowanie się do systemu:",
        "password_label": "Hasło jednorazowe",
        "after": "Po zalogowaniu przejdź do Panelu Klienta, a następnie zmień hasło na nowe, aby zapewnić bezpieczeństwo swojego konta.",
        "once": "Ze względów bezpieczeństwa hasło jednorazowe może zostać wykorzystane tylko raz.",
        "ignore": "Jeżeli nie zlecałeś odzyskiwania hasła, zignoruj tę wiadomość.",
        "closing": "Pozdrawiamy,",
        "team": "Zespół SidLee Media",
        "address_label": "Adres",
        "country": "Kanada",
        "phone_label": "Numer telefonu",
        "mail_label": "Mail",
    },
    "en": {
        "subject": "SidLee Media - password recovery",
        "title": "Password recovery",
        "greeting": "Hello,",
        "intro": "we received a request to recover access to your account on our SidLee Media platform.",
        "lead": "Below is a one-time password you can use to sign in:",
        "password_label": "One-time password",
        "after": "After you sign in, go to the Client Panel and change the password to a new one to keep your account secure.",
        "once": "For security, the one-time password can be used only once.",
        "ignore": "If you did not request a password recovery, please ignore this message.",
        "closing": "Best regards,",
        "team": "The SidLee Media Team",
        "address_label": "Address",
        "country": "Canada",
        "phone_label": "Phone",
        "mail_label": "Email",
    },
    "de": {
        "subject": "SidLee Media - Passwort wiederherstellen",
        "title": "Passwort wiederherstellen",
        "greeting": "Guten Tag,",
        "intro": "wir haben eine Anfrage zum Wiederherstellen des Zugangs zu Ihrem Konto auf unserer Plattform SidLee Media erhalten.",
        "lead": "Unten finden Sie ein Einmalpasswort, mit dem Sie sich anmelden können:",
        "password_label": "Einmalpasswort",
        "after": "Melden Sie sich danach im Kundenbereich an und ändern Sie das Passwort, um Ihr Konto zu schützen.",
        "once": "Aus Sicherheitsgründen kann das Einmalpasswort nur einmal verwendet werden.",
        "ignore": "Wenn Sie keine Passwortwiederherstellung angefordert haben, ignorieren Sie diese Nachricht.",
        "closing": "Mit freundlichen Grüßen,",
        "team": "Das SidLee Media Team",
        "address_label": "Adresse",
        "country": "Kanada",
        "phone_label": "Telefon",
        "mail_label": "E-Mail",
    },
    "fr": {
        "subject": "SidLee Media - récupération du mot de passe",
        "title": "Récupération du mot de passe",
        "greeting": "Bonjour,",
        "intro": "nous avons reçu une demande de récupération de l'accès à votre compte sur notre plateforme SidLee Media.",
        "lead": "Vous trouverez ci-dessous un mot de passe à usage unique pour vous connecter :",
        "password_label": "Mot de passe à usage unique",
        "after": "Après la connexion, ouvrez l'espace client et changez le mot de passe afin de sécuriser votre compte.",
        "once": "Pour des raisons de sécurité, le mot de passe à usage unique ne peut être utilisé qu'une seule fois.",
        "ignore": "Si vous n'avez pas demandé de récupération de mot de passe, ignorez ce message.",
        "closing": "Cordialement,",
        "team": "L'équipe SidLee Media",
        "address_label": "Adresse",
        "country": "Canada",
        "phone_label": "Téléphone",
        "mail_label": "E-mail",
    },
    "ru": {
        "subject": "SidLee Media - восстановление пароля",
        "title": "Восстановление пароля",
        "greeting": "Здравствуйте,",
        "intro": "мы получили запрос на восстановление доступа к вашему аккаунту на платформе SidLee Media.",
        "lead": "Ниже одноразовый пароль для входа в систему:",
        "password_label": "Одноразовый пароль",
        "after": "После входа откройте панель клиента и смените пароль, чтобы защитить аккаунт.",
        "once": "В целях безопасности одноразовый пароль можно использовать только один раз.",
        "ignore": "Если вы не запрашивали восстановление пароля, проигнорируйте это письмо.",
        "closing": "С уважением,",
        "team": "Команда SidLee Media",
        "address_label": "Адрес",
        "country": "Канада",
        "phone_label": "Телефон",
        "mail_label": "Почта",
    },
    "pt": {
        "subject": "SidLee Media - recuperação de palavra-passe",
        "title": "Recuperação de palavra-passe",
        "greeting": "Olá,",
        "intro": "recebemos um pedido para recuperar o acesso à sua conta na nossa plataforma SidLee Media.",
        "lead": "Abaixo encontra uma palavra-passe de utilização única para iniciar sessão:",
        "password_label": "Palavra-passe de utilização única",
        "after": "Depois de iniciar sessão, abra o painel do cliente e altere a palavra-passe para proteger a conta.",
        "once": "Por segurança, a palavra-passe de utilização única só pode ser usada uma vez.",
        "ignore": "Se não pediu a recuperação da palavra-passe, ignore esta mensagem.",
        "closing": "Cumprimentos,",
        "team": "Equipa SidLee Media",
        "address_label": "Endereço",
        "country": "Canadá",
        "phone_label": "Telefone",
        "mail_label": "E-mail",
    },
}


def password_recovery_email_copy(language: object) -> dict[str, str]:
    return PASSWORD_RECOVERY_EMAIL_COPY[normalize_activation_language(language)]
