/**
 * Countries available in the campaign creator.
 * Most codes are ISO 3166-1 alpha-2 and match a shape on the world map.
 * Small states without a map shape, plus Scotland, are still selectable in the list.
 */

export const CAMPAIGN_COUNTRY_NAME_BY_ISO: Record<string, string> = {
  ad: 'Andorra',
  ae: 'United Arab Emirates',
  af: 'Afghanistan',
  ag: 'Antigua and Barbuda',
  al: 'Albania',
  am: 'Armenia',
  ao: 'Angola',
  ar: 'Argentina',
  at: 'Austria',
  au: 'Australia',
  az: 'Azerbaijan',
  ba: 'Bosnia and Herzegovina',
  bb: 'Barbados',
  bd: 'Bangladesh',
  be: 'Belgium',
  bf: 'Burkina Faso',
  bg: 'Bulgaria',
  bh: 'Bahrain',
  bi: 'Burundi',
  bj: 'Benin',
  bn: 'Brunei',
  bo: 'Bolivia',
  br: 'Brazil',
  bs: 'Bahamas',
  bt: 'Bhutan',
  bw: 'Botswana',
  by: 'Belarus',
  bz: 'Belize',
  ca: 'Canada',
  cd: 'Democratic Republic of the Congo',
  cf: 'Central African Republic',
  cg: 'Congo',
  ch: 'Switzerland',
  ci: "Cote d'Ivoire",
  cl: 'Chile',
  cm: 'Cameroon',
  cn: 'China',
  co: 'Colombia',
  cr: 'Costa Rica',
  cu: 'Cuba',
  cv: 'Cape Verde',
  cy: 'Cyprus',
  cz: 'Czech Republic',
  de: 'Germany',
  dj: 'Djibouti',
  dk: 'Denmark',
  dm: 'Dominica',
  do: 'Dominican Republic',
  dz: 'Algeria',
  ec: 'Ecuador',
  ee: 'Estonia',
  eg: 'Egypt',
  er: 'Eritrea',
  es: 'Spain',
  et: 'Ethiopia',
  fi: 'Finland',
  fj: 'Fiji',
  fk: 'Falkland Islands',
  fm: 'Micronesia',
  fr: 'France',
  ga: 'Gabon',
  gd: 'Grenada',
  gb: 'United Kingdom',
  ge: 'Georgia',
  gh: 'Ghana',
  gl: 'Greenland',
  gm: 'Gambia',
  gn: 'Guinea',
  gq: 'Equatorial Guinea',
  gr: 'Greece',
  gt: 'Guatemala',
  gw: 'Guinea-Bissau',
  gy: 'Guyana',
  hk: 'Hong Kong',
  hn: 'Honduras',
  hr: 'Croatia',
  ht: 'Haiti',
  hu: 'Hungary',
  id: 'Indonesia',
  ie: 'Ireland',
  il: 'Israel',
  in: 'India',
  iq: 'Iraq',
  ir: 'Iran',
  is: 'Iceland',
  it: 'Italy',
  jm: 'Jamaica',
  jo: 'Jordan',
  jp: 'Japan',
  ke: 'Kenya',
  kg: 'Kyrgyzstan',
  kh: 'Cambodia',
  ki: 'Kiribati',
  km: 'Comoros',
  kn: 'St. Kitts and Nevis',
  kp: 'North Korea',
  kr: 'South Korea',
  kw: 'Kuwait',
  kz: 'Kazakhstan',
  la: 'Laos',
  lb: 'Lebanon',
  lc: 'Saint Lucia',
  li: 'Liechtenstein',
  lk: 'Sri Lanka',
  lr: 'Liberia',
  ls: 'Lesotho',
  lt: 'Lithuania',
  lu: 'Luxembourg',
  lv: 'Latvia',
  ly: 'Libya',
  ma: 'Morocco',
  mc: 'Monaco',
  md: 'Moldova',
  me: 'Montenegro',
  mg: 'Madagascar',
  mh: 'Marshall Islands',
  mk: 'North Macedonia',
  ml: 'Mali',
  mm: 'Myanmar',
  mn: 'Mongolia',
  mo: 'Macao',
  mr: 'Mauritania',
  mt: 'Malta',
  mu: 'Mauritius',
  mv: 'Maldives',
  mw: 'Malawi',
  mx: 'Mexico',
  my: 'Malaysia',
  mz: 'Mozambique',
  na: 'Namibia',
  nc: 'New Caledonia',
  ne: 'Niger',
  ng: 'Nigeria',
  ni: 'Nicaragua',
  nl: 'Netherlands',
  no: 'Norway',
  np: 'Nepal',
  nr: 'Nauru',
  nz: 'New Zealand',
  om: 'Oman',
  pa: 'Panama',
  pe: 'Peru',
  pg: 'Papua New Guinea',
  ph: 'Philippines',
  pk: 'Pakistan',
  pl: 'Poland',
  pr: 'Puerto Rico',
  pt: 'Portugal',
  pw: 'Palau',
  py: 'Paraguay',
  qa: 'Qatar',
  ro: 'Romania',
  rs: 'Serbia',
  ru: 'Russia',
  rw: 'Rwanda',
  sa: 'Saudi Arabia',
  sb: 'Solomon Islands',
  sc: 'Seychelles',
  scotland: 'Scotland',
  sd: 'Sudan',
  se: 'Sweden',
  sg: 'Singapore',
  si: 'Slovenia',
  sk: 'Slovakia',
  sl: 'Sierra Leone',
  sm: 'San Marino',
  sn: 'Senegal',
  so: 'Somalia',
  sr: 'Suriname',
  ss: 'South Sudan',
  st: 'Sao Tome and Principe',
  sv: 'El Salvador',
  sy: 'Syria',
  sz: 'Eswatini',
  td: 'Chad',
  tg: 'Togo',
  th: 'Thailand',
  tj: 'Tajikistan',
  tl: 'Timor-Leste',
  tm: 'Turkmenistan',
  tn: 'Tunisia',
  to: 'Tonga',
  tr: 'Turkey',
  tt: 'Trinidad and Tobago',
  tv: 'Tuvalu',
  tw: 'Taiwan',
  tz: 'Tanzania',
  ua: 'Ukraine',
  ug: 'Uganda',
  us: 'United States',
  uy: 'Uruguay',
  uz: 'Uzbekistan',
  va: 'Vatican City',
  vc: 'Saint Vincent and the Grenadines',
  ve: 'Venezuela',
  vn: 'Vietnam',
  vu: 'Vanuatu',
  ws: 'Samoa',
  xk: 'Kosovo',
  ye: 'Yemen',
  za: 'South Africa',
  zm: 'Zambia',
  zw: 'Zimbabwe',
};

export const CAMPAIGN_COUNTRY_CODES = Object.keys(CAMPAIGN_COUNTRY_NAME_BY_ISO);

/** Blocked countries present as shapes on the world map. */
export const BLOCKED_CAMPAIGN_MAP_CODES = [
  'by',
  'cn',
  'cu',
  'ir',
  'kp',
  'ru',
  'sy',
] as const;

/**
 * Blocked regions without dedicated map shapes on the current SVG
 * (still shown in the select as disabled).
 */
export const BLOCKED_CAMPAIGN_REGION_CODES = [
  'crimea',
  'donetsk',
  'luhansk',
  'ps',
] as const;

const BLOCKED_CAMPAIGN_CODES = new Set<string>([
  ...BLOCKED_CAMPAIGN_MAP_CODES,
  ...BLOCKED_CAMPAIGN_REGION_CODES,
]);

export const BLOCKED_REGION_NAME_BY_CODE: Record<string, string> = {
  crimea: 'Crimea',
  donetsk: 'Donetsk',
  luhansk: 'Luhansk',
  ps: 'Palestine',
};

export const CAMPAIGN_COUNTRY_LIST_CODES = [
  ...CAMPAIGN_COUNTRY_CODES,
  ...BLOCKED_CAMPAIGN_REGION_CODES,
];

export function campaignCountryLabelKey(code: string): string {
  return `app.countries.${code}`;
}

export function isBlockedCampaignCountry(code: string): boolean {
  return BLOCKED_CAMPAIGN_CODES.has(code);
}

export function isSelectableCampaignCountry(code: string): boolean {
  return code in CAMPAIGN_COUNTRY_NAME_BY_ISO && !isBlockedCampaignCountry(code);
}
